### ISSUE TITLE
Support Vault 0.11 and greater

### ISSUE THREAD

**Issue by azuretek** [coreos/vault-operator#354]
I love the vault operator, it simplifies a lot of the issues around deploying vault in a redundant way with ephemeral storage. Also the simplicity of backing up and restoring is great too.

The only issues is that we're stuck on an old version of vault and we want to upgrade. Is there a reason the operator can't just run a publicly available vault image? As far as I can tell all the vault API endpoints in use haven't changed between v0.9 and v0.11, and I'm not aware of any custom modifications to vault that allow the operator to function.

Is there a reason we can't support the newer versions of vault?

**Comment by azuretek** [comment]
So I was able to upgrade by creating a vault image that installs curl and bash and setting my `baseImage` and `version` to match my docker image.

Apparently that's all that's required to make this work, though I don't understand why the image isn't provided by the maintainers of this project.

**Comment by ficofer** [comment]
@azuretek I been trying to do this to win GUI capabilities do you have a readme or step by step of your docker file to have as a base ?

**Comment by bazzilio** [comment]
look to https://github.com/coreos/vault-operator/issues/332

**Comment by azuretek** [comment]
@ficofer sorry for the late response but for posterity here's our docker file

```
FROM vault:0.11.5

RUN apk add --no-cache curl
```

You'll want to pin that to whatever version you need.
