### ISSUE TITLE
Error initializing storage of type etcd: failed to get etcd API version: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 10.101.6.170:2379: getsockopt: connection refused

### ISSUE THREAD

**Issue by paragpoddar** [coreos/vault-operator#366]
After deploying vault cluster, getting the error 
`Error initializing storage of type etcd: failed to get etcd API version: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 10.101.6.170:2379: getsockopt: connection refused`

I have followed 
https://github.com/coreos/vault-operator#configuring-rbac
https://github.com/coreos/vault-operator#deploying-the-etcd-operator
https://github.com/coreos/vault-operator#deploying-the-vault-operator
https://github.com/coreos/vault-operator#deploying-the-vault-operator

**Comment by RussellGilmore** [comment]
Are you running this on EKS?

**Comment by roaddemon** [comment]
I'm getting the same error on GKE.

**Comment by roaddemon** [comment]
For me the etc cluster isn't coming up properly.  The check-dns Init Container is just spinning.

```
$ kc get po -l app=etcd
NAME                      READY   STATUS     RESTARTS   AGE
example-etcd-xz598qsp54   0/1     Init:0/1   0          165m

```
Logs from init container:
```
$ kc logs example-etcd-xz598qsp54 -c check-dns
Server:         10.23.240.10
Address:        10.23.240.10:53

** server can't find example-etcd-xz598qsp54.example-etcd.default.svc: NXDOMAIN

*** Can't find example-etcd-xz598qsp54.example-etcd.default.svc: No answer

(Repeats every two seconds ad infinitum)
```

Init container is checking dns:

```
 Command:
      /bin/sh
      -c

                            while ( ! nslookup example-etcd-xz598qsp54.example-etcd.default.svc )
                            do
                              sleep 2
                            done
```

**Comment by paragpoddar** [comment]
@RussellGilmore  yes

**Comment by Switcher05** [comment]
Running into this from a Rancher App helm template on:

Rancher | v2.3.0-alpha5
User Interface | v2.3.2
Helm | v2.10.0-rancher11
Machine | v0.15.0-rancher8-1
Helm template name: vault-operator
version: 0.1.2

Bare metal custom Ubuntu 16 nodes
